version: '3'

services:
  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - "6389:6389"
  web:
    build: ./
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    links:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://cache
