version: '3'

services:
  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - "6389:6389"
  web:
    build: ./
    ports:
      - "3007:3007"
      - "3008:3008"
    volumes:
      - .:/usr/src/app
    links:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3007
      - REDIS_URL=redis://cache
